### ISSUE TITLE
Best certificate match doesn't work well for letsencrypt certificates

### ISSUE THREAD

**Issue by dadittoz** [dmp1ce/nginx-proxy-letsencrypt#12]
Current letsencrypt certificates must exactly match hostname. So substituting _`domain.com.crt`_ for _`www.domain.com.crt`_ renders an SSL error.

This line of code in `nginx.tmpl` is responsible for generating such substitution

```
{{/* Get the best matching cert  by name for the vhost. */}}
{{ $vhostCert := (closest (dir "/etc/nginx/certs") (printf "%s.crt" $host))}}
```

**Comment by dmp1ce** [comment]
I see. I didn't know nginx-proxy did that, but you can avoid the error by asking Let's Encrypt for both certificates. You can set `LETSENCRYPT_HOST="www.domain.com,domain.com"`.

**Comment by dadittoz** [comment]
@dmp1ce Well, I can avoid that by changing that line in `nginx.tmpl` ;) But the problem actually is with the domain that has a lot of subdomains, so I hit the rate-limit of a 5 subdomains in a 7 days window. So it's going to take days/weeks until I receive `www` subdomain certificate while my proxy replies with a wrong certificate and render SSL error for browsers.

I've fixed it by changing the line to:

```
{{ $vhostCert := printf "%s.crt" $host }}
```

The reason I've opened a new issue, rather than a pull request is that I am not sure if this is the best way to do it. But once thing I am sure of is that it's just technically incorrect to use best matching certificate in letsencrypt-proxy while letsencrypt.org has a strict per subdomain certificate policy.

**Comment by JrCs** [comment]
If thing it can works if we create a certificate with multi-domain in it.
Need to try...

**Comment by dadittoz** [comment]
Yeah, I looks like multiple "-d" options per simp_le call should do the trick.

**Comment by dadittoz** [comment]
Everything seems to work fine with multiple -d options. I've added `letsencrypt_service` pull request. Feel free to modify it to your coding standards if you wish :)
