### ISSUE TITLE
Selected IO plugins do not cover the following components: account_key.

### ISSUE THREAD

**Issue by adamlc** [dmp1ce/nginx-proxy-letsencrypt#15]
Not sure whats causing this for Lets Encrypt? I've used this proxy on another domain that was in the closed beta and it worked fine. Not sure if theres a different URL for the ACME server now?

Seems to be coming from here, not sure if it helps: https://github.com/kuba/simp_le/blob/7caa31c189dc72a0f18e4fcc021132212f6848d1/simp_le.py#L861

**Comment by hadim** [comment]
Please, see https://github.com/dmp1ce/nginx-proxy-letsencrypt/issues/14

**Comment by adamlc** [comment]
Brilliant thanks! I'll get this open until #14 is fixed so people dont open more Issues :+1:

**Comment by adamlc** [comment]
Works now thanks to #16 :)
