### ISSUE TITLE
Force https on containers with LETSENCRYPT_HOST

### ISSUE THREAD

**Issue by benjick** [dmp1ce/nginx-proxy-letsencrypt#19]
Would this be possible?

**Comment by dmp1ce** [comment]
I think it is already supposed to do that. Do you have a case where it doesn't work? See here: https://github.com/dmp1ce/nginx-proxy-letsencrypt#how-ssl-support-works

**Comment by dmp1ce** [comment]
String Transport Security should also be set so browsers will always try to visit the site using TLS. See the nginx template: https://github.com/dmp1ce/nginx-proxy-letsencrypt/blob/master/nginx.tmpl#L138

**Comment by benjick** [comment]
Yep, you're right. Maybe I visited port 80 before the cert was generated or something. Sorry

**Comment by dmp1ce** [comment]
No problem. I'm sure many others have the same question.
