### ISSUE TITLE
Redirect loop with https

### ISSUE THREAD

**Issue by dmitrym0** [dmp1ce/nginx-proxy-letsencrypt#27]
Hello dmp1ce,

Thank you for a wonderful project. It's really quite unbelievable how easy it is to connect the pieces now, to get a fully SSL-enabled application out there. That said, I have a small wrinkle that I'm not sure what to do with. Basically, when accessing my rails application, I end up with a weird redirect loop on every second request:

> curl -I -X GET https://potatr.duckdns.org/users/sign_in
> 
> ```
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.9.6
> Date: Wed, 23 Dec 2015 03:51:20 GMT
> Content-Type: text/html
> Content-Length: 184
> Connection: keep-alive
> Location: https://potatr.duckdns.org/users/sign_in
> Strict-Transport-Security: max-age=31536000
> ```

and in the nginx-proxy-letsencrypt container:

```
nginx.1      | potatr.duckdns.org 192.235.240.9 - - [23/Dec/2015:03:51:20 +0000] "GET /users/sign_in HTTP/1.1" 301 184 "-" "curl/7.37.1"
nginx.1      | potatr.duckdns.org 172.17.0.4 - - [23/Dec/2015:03:51:20 +0000] "GET /users/sign_in HTTP/1.1" 301 184 "-" "curl/7.37.1"
```

where 192.\* is my request, and 172.\* is the container running my app. 

Here's the second request:

> curl -I -X GET https://potatr.duckdns.org/users/sign_in

```
HTTP/1.1 200 OK
Server: nginx/1.9.6
Date: Wed, 23 Dec 2015 03:56:40 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Vary: Origin
ETag: W/"9585f8f7ff8d9d2a99003128be83023a"
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Runtime: 0.024472
X-Request-Id: 15dfe9a5-dd39-49d9-ba1c-ee0c86b38ce3
Set-Cookie: _potatr_session=TWRlTDloUUIvYmNoUU5MK00yU0ZHWWxrZXJEWHhnc3kranNrZmcySVAray9sak03WS8xVVpXWlowdnp3TEhONjdRSFU3OFZnODRROEtza0lMV2diNlBuaXU3TFRlTmF4NWRvWWk5Y3ZGRE9LWWNlWWtDM2NidGNvdEpGalRJMENEVDhieGRZbUJBWHZwci9VSElSMTlnPT0tLWlhRDlzVk5xZkRqY2tnNFg1U2xGakE9PQ%3D%3D--4d8cf4c536109a2cfe6dcfd3861dfc1f3801e0d9; path=/; HttpOnly
X-Powered-By: Phusion Passenger 5.0.15
Strict-Transport-Security: max-age=31536000
```

and in the proxy container:

```
nginx.1      | potatr.duckdns.org 192.235.240.9 - - [23/Dec/2015:03:56:40 +0000] "GET /users/sign_in HTTP/1.1" 200 4757 "-" "curl/7.37.1"
```

Any idea what's going on here? It almost looks like the app inside the container redirecting back to itself. Can you spot anything obviously wrong?

Thanks again.

**Comment by dmp1ce** [comment]
It looks like the second request was successful. It returned code 200. I'm not sure what is going on with the first request.

**Comment by dmitrym0** [comment]
Thanks David.

It only seems to be happening with the nginx-proxy-letsencrypt. If I talk to my container directly, everything is fine. It's also only every **SECOND** request that behaves that way. Could it have something to do with the fact that my container ([passenger-docker](https://github.com/phusion/passenger-docker)) is running an nginx internally as well?

**Comment by dmp1ce** [comment]
I run nginx internally with nginx-proxy-letsencrypt and I haven't noticed this. It could possibly the be passenger setup or Rails app setup though. I'll try to test with passenger-docker as soon as I can.

**Comment by dmitrym0** [comment]
I haven't ruled my app out completely, so I'll test it out as well. The image I'm using [passenger-full](https://hub.docker.com/r/phusion/passenger-full/).

**Comment by dmitrym0** [comment]
David, 

I ruled my app out. I reproduced this with a very simple rails app. You can find the docker image here: https://hub.docker.com/r/dmarkush/basic-rails-app/ (and the github repository here: https://github.com/dmitrym0/basic-rails-app).

The app has two URLs:
- root (`/`) of the site will return a hello world in json. That seems to work fine.
- requesting `/people` however is where it goes nuts. It doesn't like POST requests, they result in an eventual GET instead.

This is how I run it:

```
docker run -d -p 80:80 -p 443:443  \
    -e VIRTUAL_HOST="potatr.duckdns.org" \
    -e LETSENCRYPT_HOST="potatr.duckdns.org" \ 
    -e LETSENCRYPT_EMAIL="dmitrym@gmail.com" \
    -v `pwd`:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro dmp1ce/nginx-proxy-letsencrypt
```

and

```
docker run -d -p 8888:80  \
    -e VIRTUAL_HOST="potatr.duckdns.org" \
    -e LETSENCRYPT_HOST="potatr.duckdns.org" \
    -e LETSENCRYPT_EMAIL="dmitrym@gmail.com" dmarkush/basic-rails-app
```

**Comment by dmp1ce** [comment]
Don't put the `VIRTUAL_HOST` and `LETSENCRYPT_*` variables in the nginx-proxy container. That is probably what is causing the crazy redirects. The documentation was wrong at one point which may have been what you used to setup your project.

Here is what I did:

``` bash
$ cat start_proxy.bash                  
#!/bin/bash
docker run -d -p 80:80 -p 443:443  \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    dmp1ce/nginx-proxy-letsencrypt
$ cat start_rails.bash 
#!/bin/bash
docker run -d -p 8888:80  \
    -e VIRTUAL_HOST="letsencrypt.upgradeya.com" \
    -e LETSENCRYPT_HOST="letsencrypt.upgradeya.com" \
    -e LETSENCRYPT_EMAIL="daveparrish@tutanota.com" dmarkush/basic-rails-app
```

**Comment by dmitrym0** [comment]
Doh! That fixed it. 

Thanks David, happy holidays.
