### ISSUE TITLE
nginx config not updated to use SSL when certificates is created/downloaded

### ISSUE THREAD

**Issue by hadim** [dmp1ce/nginx-proxy-letsencrypt#3]
Having a pretty standard configuration and nginx-proxy-letsencrypt usage, certificates are correctly downloaded and saved into `/etc/nginx/certs/` but the nginx config is not updated.

It works when I manually enter in the container and execute the following command `/usr/local/bin/docker-gen -watch -only-exposed -notify "/app/update_nginx" /app/nginx.tmpl /etc/nginx/conf.d/default.conf`.

Any idea ?

**Comment by dmp1ce** [comment]
I had the same issue. The only work around for now is to restart nginx-proxy.

I think we can add a command to regenerate the default.conf if a certificate is downloaded.

**Comment by hadim** [comment]
Fix by #6
