### ISSUE TITLE
Possibility to proxy non containers

### ISSUE THREAD

**Issue by nicam** [dmp1ce/nginx-proxy-letsencrypt#30]
Hi There, thank you for your great bundle! I'm looking for a way to proxy & create Let's Encrypt Certificates for vhosts that don't have a container. For instance some remote control interface that is running on a raspberry pi. Right now I'm using a second (regular) nginx container to achieve this:

client --(https)--> nginx-proxy ---(http)---> nginx --(http)---> raspberrypi

It works but it's a bit inefficient to have 2 proxies :). Is there already a way to tell nginx-proxy about a vhost that isn't a container but still receive an SSL certificate from letsencrypt or would that be a new feature?

Best regards.

Pascal Helfenstein

**Comment by dmp1ce** [comment]
I don't think that is going to be easy to accomplish with this project. Probably you'll want to build the Let's Encrypt functionality into your first Nginx container. There is also a companion container @JrCs built which may give you an ideas for a way to inject the certificate into your server. https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
