### ISSUE TITLE
http upload size limit

### ISSUE THREAD

**Issue by zlwu** [dmp1ce/nginx-proxy-letsencrypt#31]
Is it possible to enlarge the http upload size limit in nginx.tmpl? Here is a link for the reason. http://stackoverflow.com/questions/7489813/github-push-error-rpc-failed-result-22-http-code-413

**Comment by dmp1ce** [comment]
I think you'll want to add your own custom configuration. https://github.com/jwilder/nginx-proxy#custom-nginx-configuration
