### ISSUE TITLE
certificates renewal

### ISSUE THREAD

**Issue by hadim** [dmp1ce/nginx-proxy-letsencrypt#4]
What happen when a certificate expire ? Is there is a way to automatically renew it ?

**Comment by hadim** [comment]
According to simp_le manifest, renewal is automatic. So maybe `letsencrypt_service` should be regularly executed in order to check certificates validity.

That way container don't need to be restarted manually.

What do you think ?

**Comment by dmp1ce** [comment]
I'm pretty sure the certificate is checked for renewal every hour. If the certificate is within the default threshold set by simp_le then simp_le will ask Let's Encrypt for another certificate. I haven't tested it but that is the way it is intended to work.

One way to test the functinality is to set the simp_le certificate expire to something that will cause it to request a new certificate every hour or less.

I have verified from the docker logs that simp_le is checking the certificate to see if it has expired.

**Comment by hadim** [comment]
Awesome.
